site_name: ironBars Documentation
site_dir: documentation  # <- must NOT be 'docs'

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      options:
            show_source: false
            show_root_toc_entry: false
            filters:
              exclude:
                - "^__.*$"  # hide dunder methods if you want